import Head from 'next/head'
import React, { useEffect, useState } from 'react'

export default function Home() {
  const [timer, setTimer] = useState(3)
  const [playing, setPlaying] = useState(false)
  useEffect(() =>{
    if( playing == false){
      return;
    }
    
    const countDown = setTimeout(()=>{
      setTimer(c => c - 1)
    }, 1000)
    
    if(timer == -1){
      setPlaying(false)
      setTimer(3)
    }
    return () =>  clearTimeout(countDown)

    
  },[timer, playing])

 const startPlaying = () => {
    setPlaying(true)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{timer}</p>
      <button onClick={startPlaying}>button</button>

    </>
  )
}
